conv-opts = "يتيح تحويل الملفات بين تنسيقات toml و yaml و json و ron"

from = "يحدد ملف الإدخال."

conv-to = "يحدد تنسيق / ملف الإخراج، يمكن استخدامه عدة مرات."
conv-to-help = """
إذا كان الملف **test.json** موجودًا في الدليل الحالي، يمكنك استخدام `conv test.json -t yml` لتحويله إلى yml (yaml)،
أو يمكنك تحديد مسار الملف يدويًا: `conv test.json -t /tmp/test.yml`

التنسيقات المدعومة تعتمد على الميزات التي تم تمكينها في هذه الحزمة ، وليست جميع الميزات تم تمكينها بشكل افتراضي.

بالإضافة إلى ذلك، يجب أن تعرف قبل استخدام هذه الأمر الآتي:
- 1. سيتم إعادة تسمية المسارات غير المحددة المحددة بشكل تلقائي.
     - 1.1 فقط الملفات ذات المستوى الواحد سيتم تشخيصها بأنها صيغة ملف، وليس مسار
       عند استخدام `conv test.toml -t ron` ، سيتم تغيير اسم الملف المخرج إلى `test.ron` بدلاً من `ron`.
       إذا كنت لا تريد هذه الميزة، فيرجى استخدام `-t ./ron` أو `-t $PWD/ron`..
     - 1.2 يشير إلى الدليل وليس الملف.
       على سبيل المثال:`-t /tmp/`، يمكننا وضع `test.toml` فقط في الدليل الفرعي لـ `/tmp/`، وليس الغطاء `/tmp` نفسه.
       إذا كنت لا تريد هذه الميزة، فيرجى استخدام مسار الملف الكامل (و ليس المسار الفرعي)، على سبيل المثال، `-t /tmp/xx.toml` بدلاً من `-t /tmp/`.
- 2. عندما لا تُستدعى `--save`، لن يتم حفظ الملفات التي تم تحويلها بشكل تلقائي.
- 3. عند استدعاء `--save`، لا يجوز أن يكون الملف الناتج هو نفس الملف الذي تم دخوله.
- 4. لا يتم الاحتفاظ بالتعليقات في الملفات التي تم تحويلها."""

save = "عند استدعاء هذا الخيار، سيتم حفظ الملف الذي حُدِّدَ باستخدام `--to`."
