auto-detection-failed = "فورماتىنى ئاپتوماتىك بايقاش مەغلۇب بولدى.قولدا بەلگىلەڭ."
conv-error = "ئايلاندۇرۇش خاتالىقى"
dst = "نىشان ھۆججەت يولى"
"invalid-json1.0" = "ھۆججەت ئىناۋەتلىك ` `JSON 1.0 فورمات ئەمەس, «JSONEN5`» دەپ تەرىۋالماقچى."
not-included = """
بۇ ئىككىلىك ** ** سۆزنى ئۆز ئىچىگە ئالمايدۇ ** مۇناسىۋەتلىك فورماتنىڭ ئايلانما ئىقتىدارىنى ئۆز ئىچىگە ئالمايدۇ.
«يۈك ساندۇقىڭىز بىلەن مۇناسىۋەتلىك ئىقتىدارنى قوزغىتىشىڭىز كېرەك. ۋە قايتا يېزىلغان.
ئەگەر بۇ يۇمشاق دېتال مۇناسىپ ئىقتىدارنى ئۆز ئىچىگە ئالمىسا, بىر مەسىلىنى يوللاڭ."""
not-saved = "تۆۋەندىكى مەزمۇن *** نى **** نى ساقلىمايدۇ ** ساقلانمايدۇ."
unknown-fmt = "نامەلۇم ھۆججەت شەكلى"
unsupported = "قوللىمايدىغان فورمات ئۆزگەرتىش"
