conv-opts = "toml、yaml、json、ronなどの形式間で変換する"

from = "入力ファイルを指定します"

conv-to = "出力形式/ファイルを指定します。複数回呼び出すことができます。"
conv-to-help = """
現在のディレクトリに **test.json** ファイルがある場合、`conv test.json -t yml` を呼び出してyml (yaml)に変換することができます。
また、ファイルパスを手動で指定することもできます。`conv test.json -t /tmp/test.yml`

サポートされている形式は、このパッケージで有効になっている機能によって異なります。全機能が自動的に有効になるわけではありません。

さらに、使用前に知っておく必要があることがあります。
- 1. 具体的なファイルパス以外にも自動的に名前を変更します。
  - 1.1: ファイルパスが一段階だけの場合、ファイル形式と判断されます。
    `conv test.toml -t ron` を呼び出すと、出力ファイルが `test.ron` に自動変更されるため、 `ron` にはなりません。
    この機能が必要ない場合は、`-t ./ron`または`-t $PWD/ron`を使用してください。
  - 1.2: ディレクトリを指す場合
    `-t /tmp/` のように指定した場合、 `test.toml` を `/tmp/` のサブディレクトリに置く必要があります。`/tmp` 自体を上書きすることはできません。
    この機能が必要ない場合は、完全なファイルパス（ディレクトリではない）を指定してください。たとえば、`-t /tmp/xx.toml`のように、`-t /tmp/`ではなく、`-t /tmp/xx.toml`を使用します。
- 2. `--save` を呼び出さない場合、指定されたファイルは自動的に保存されません。
- 3. `--save` を呼び出す場合、convサブコマンドの入力と出力が同じファイルになることはできません。
- 4. 変換後のファイルにはコメントが含まれません。"""

save = "このオプションを呼び出すと、`--to` で指定されたファイルが保存されます。"
