auto-detection-failed = "Не атрымалася аўтаматычна выявіць фармат.Калі ласка, укажыце ўручную."
conv-error = "Памылка пераўтварэння"
currently-supported = "У цяперашні час падтрымліваецца спіс фарматаў:"
dst = "шлях файла прызначэння"
"invalid-json1.0" = "Файл не з'яўляецца сапраўдным фарматам `json 1.0`, спрабуючы разбіваць як `json5` ..."
not-included = """
Гэты двайковы ** не ўключае ** функцыянальнасць пераўтварэння для адпаведнага фармату.
Вам неабходна ўключыць адпаведную функцыю ў вашым `chargo.toml` і Recompile.
Калі гэта праграмнае забеспячэнне не ўключае адпаведную функцыянальнасць, калі ласка, адпраўце праблему."""
not-saved = "Наступны змест ** не будзе захаваны **, таму што `--save` не быў выкліканы."
not-support-deser-sexp = "** Пакуль яшчэ не падтрымліваецца **: пераўтварэнне з `Lisp S-Expression` да` іншых фарматаў '"
unknown-fmt = "Невядомы фармат файла"
unsupported = "Перакладзенае пераўтварэнне фармату"
