auto-detection-failed = "format ကိုအလိုအလျောက်စစ်ဆေးရန်ပျက်ကွက်ခဲ့သည်။ကျေးဇူးပြုပြီးကိုယ်တိုင်ကိုယ်ကျဖော်ပြပါ"
conv-error = "ကူးပြောင်းခြင်းအမှား"
currently-supported = "လက်ရှိတွင်ထောက်ပံ့ထားသောပုံစံများစာရင်း -"
dst = "destination file path"
"invalid-json1.0" = "ဖိုင်သည်ခိုင်လုံသော `JSON 1.0` format မဟုတ်ဘဲ `JSON5 `` `json5` asse ကိုခွဲခြမ်းစိတ်ဖြာရန်ကြိုးစားနေသည်။"
not-included = """
ဤ binary ** သည်သက်ဆိုင်ရာပုံစံအတွက်ပြောင်းလဲခြင်းလုပ်ဆောင်နိုင်စွမ်းကိုမပါ 0 င်ပါ။
သင်၏ `Cargo.toml` တွင်သက်ဆိုင်ရာအင်္ဂါရပ်ကို enable လုပ်ရန်လိုအပ်သည်။
အကယ်. ဤဆော့ (ဖ်) ဝဲသည်သက်ဆိုင်ရာလုပ်ဆောင်နိုင်စွမ်းမပါရှိပါက ကျေးဇူးပြု. ပြ an နာကိုတင်ပါ။"""
not-support-deser-sexp = "** ** မထောက်ပံ့ရသေးပါ။"
unknown-fmt = "မသိသောဖိုင်ပုံစံ"
unsupported = "unsupported format ပြောင်းလဲခြင်း"
