conv-opts = "टॉमल, याम्ल, जेसन और रोन फ़ॉर्मेट के बीच परिवर्तन करें"

from = "इनपुट फ़ाइल का नाम निर्दिष्ट करें"

conv-to = "आउटपुट फॉर्मेट/फ़ाइल का नाम निर्दिष्ट करें, एक से अधिक बार कॉल कैसे करें"
conv-to-help = """
यदि वर्तमान निर्देशिका में **test.json** फ़ाइल मौजूद है, तो आप `conv test.json -t yml` कॉल करके इसे yml (yaml) में बदल सकते हैं,
या आप मैन्युअली फ़ाइल पथ निर्दिष्ट कर सकते हैं: `conv test.json -t /tmp/test.yml`

यह पैकेज इनग्रीडिएंट्स के आधार पर समर्थित फ़ॉर्मेट का निर्धारण करता है, सभी फ़ंक्शंस डिफ़ॉल्ट रूप से समर्थित नहीं होते हैं।

इसके अतिरिक्त, आपको इस्तेमाल से पहले जानना आवश्यक है कि -
- 1. यह गैर विशिष्ट फ़ाइल पथों को स्वतः नामित करेगा।
  - 1.1: एक स्तर की केवल एक फ़ाइल को फ़ाइल फ़ॉर्मेट के रूप में गणना किया जाएगा, न कि फ़ाइल पथ के रूप में
    `conv test.toml -t ron` कॉल करते समय, उत्पादित फ़ाइल अपने आपको `test.ron` बनाएगी, न कि `ron`।
    यदि आपकी ज़रूरत नहीं है, तो कृपया `-t ./ron` या `-t $PWD/ron` के रूप में स्पष्ट फ़ाइल पथ का उपयोग करें।
  - 1.2: एक निर्दिष्ट डायरेक्टरी को लक्ष्य बनाया गया है, न कि फ़ाइल
    उदाहरण के लिए, `-t /tmp/` केवल `/tmp/` के उप-स्तर में `test.toml` रख सकते हैं, `/tmp"""
