auto-detection-failed = "ቅርጸት በራስ-ሰር ለመምረጥ አልተሳካም.እባክዎ እራስዎ ይጥቀሱ."
conv-error = "የውድር ስህተት"
currently-supported = "በአሁኑ ጊዜ የተደገፉ ቅርፀቶች ዝርዝር:"
dst = "የመድረሻ ፋይል መንገድ"
"invalid-json1.0" = "ፋይሉ ትክክለኛ jdson 1.0 ቅርጸት, እንደ `json5` ወደታች ለመሞከር በመሞከር ላይ ..."
not-included = """
ይህ ሁለትዮሽ ** ተገቢውን ቅርጸት የውይይት ተግባሩን አያካትትም.
ተገቢውን ባህሪ በ `ኘካሪ.` `ዎ ውስጥ ባለው የጭነት መኪናዎ ውስጥ ማንቃት ያስፈልግዎታል.
ይህ ሶፍትዌር ተጓዳኝ ተግባሩን የማያካትት ከሆነ እባክዎን አንድ ጉዳይ ያስገቡ."""
not-saved = "የሚከተለው ይዘት ** አይሰጥም *** አይቀመጥም *** መቀመጥ የለበትም."
unknown-fmt = "ያልታወቀ ፋይል ቅርጸት"
unsupported = "የማይደገፍ ቅርጸት ልወጣ"
