auto-detection-failed = "ಸ್ವರೂಪವನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಕಂಡುಹಿಡಿಯಲು ವಿಫಲವಾಗಿದೆ.ದಯವಿಟ್ಟು ಹಸ್ತಚಾಲಿತವಾಗಿ ನಿರ್ದಿಷ್ಟಪಡಿಸಿ."
conv-error = "ಪರಿವರ್ತನೆ ದೋಷ"
currently-supported = "ಪ್ರಸ್ತುತ ಬೆಂಬಲಿತ ಸ್ವರೂಪಗಳ ಪಟ್ಟಿ:"
dst = "ಗಮ್ಯಸ್ಥಾನ ಫೈಲ್ ಮಾರ್ಗ"
"invalid-json1.0" = "ಫೈಲ್ ಮಾನ್ಯ `JSON 1.0` ಸ್ವರೂಪವಲ್ಲ, `json5` ಎಂದು ಪಾರ್ಸ್ ಮಾಡಲು ಪ್ರಯತ್ನಿಸುತ್ತಿದೆ ..."
not-included = """
ಈ ಬೈನರಿ ** ಸಂಬಂಧಿತ ಸ್ವರೂಪಕ್ಕಾಗಿ ** ಪರಿವರ್ತನೆ ಕಾರ್ಯವನ್ನು ಒಳಗೊಂಡಿಲ್ಲ.
ನಿಮ್ಮ `ಕಾರ್ಗೋ.ಟೊಮ್ಲ್` ಮತ್ತು ಮರು ಕಂಪೈಲ್ನಲ್ಲಿ ನೀವು ಸಂಬಂಧಿತ ವೈಶಿಷ್ಟ್ಯವನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಬೇಕಾಗಿದೆ.
ಈ ಸಾಫ್ಟ್‌ವೇರ್ ಅನುಗುಣವಾದ ಕಾರ್ಯವನ್ನು ಒಳಗೊಂಡಿರದಿದ್ದರೆ, ದಯವಿಟ್ಟು ಸಮಸ್ಯೆಯನ್ನು ಸಲ್ಲಿಸಿ."""
not-saved = "ಈ ಕೆಳಗಿನ ವಿಷಯವನ್ನು ** ಉಳಿಸಲಾಗುವುದಿಲ್ಲ ಏಕೆಂದರೆ `--save` ಎಂದು ಕರೆಯಲಾಗುವುದಿಲ್ಲ."
not-support-deser-sexp = "** ಇನ್ನೂ ಬೆಂಬಲಿತವಾಗಿಲ್ಲ **: `ಲಿಸ್ಪ್ ಎಸ್-ಎಕ್ಸ್‌ಪ್ರೆಶನ್'ನಿಂದ` ಇತರ ಸ್ವರೂಪಗಳು'ಗೆ ಪರಿವರ್ತಿಸುವುದು"
unknown-fmt = "ಅಜ್ಞಾತ ಫೈಲ್ ಫಾರ್ಮ್ಯಾಟ್"
unsupported = "ಬೆಂಬಲಿಸದ ಸ್ವರೂಪ ಪರಿವರ್ತನೆ ಪರಿವರ್ತನೆ"
