[workspace]
members = ["core", "cli"]
resolver = "2"

[profile.release]
panic = "unwind"

[profile.thin]
inherits = "release"
panic = "abort"
# debug = false
strip = true
lto = "thin"

[profile.fat]
inherits = "thin"
lto = "fat"
opt-level = "z"
