auto-detection-failed = "Форматты автоматтык түрдө аныктай алган жок.Сураныч, кол менен белгилеңиз."
conv-error = "Конверсиялык ката"
currently-supported = "Учурда колдоого алынган форматтар тизмеси:"
dst = "көздөгөн файл жол"
"invalid-json1.0" = "Файл `JSON 1.0` 'форматына ылайык эмес"
not-included = """
Бул экилик ** камтылбайт ** Качан, тиешелүү форматта конверсиялык функция.
Сиздин `Cargo.toml` жана Recial'до тиешелүү функцияны иштетишиңиз керек.
Эгерде бул программа тиешелүү функционалдык камтылбаса, анда маселени тапшырыңыз."""
not-saved = "Төмөнкү мазмун ** ** сакталбайт ** сакталбайт, анткени `--save` деп аталган жок."
not-support-deser-sexp = "** Бирок колдоого алынбайт **: `Lisp S-сөз айкашы`"
unknown-fmt = "Белгисиз файл Форматы"
unsupported = "Форматты колдоого алынбаган өзгөртүү"
