conv-opts = "toml, yaml, json, ron 등의 형식 간 변환"

from = "입력 파일을 지정합니다."

conv-to = "지원되는 출력 형식/파일을 지정하고, 여러 번 사용할 수 있습니다."
conv-to-help = """
현재 디렉토리에 **test.json** 파일이 있다면, `conv test.json -t yml`을(를) 호출하여 yml(yaml)로 변환할 수 있습니다.
또한 수동으로 파일 경로를 지정할 수도 있습니다: `conv test.json -t /tmp/test.yml`

지원되는 형식은 패키지에서 활성화된 기능에 따라 다릅니다. 모든 기능이 기본적으로 활성화되지는 않습니다.

또한 사용하기 전에 알아둬야 할 사항이 있습니다.
- 1. 명시적인 파일 경로가 아닌 경우 자동으로 이름이 변경됩니다.
    - 1.1: 단일 파일 계층 구조만 파일 형식으로 인식됩니다.
    `conv test.toml -t ron`을(를) 호출하면 출력 파일은 `ron`이 아니라 자동으로 `test.ron`으로 변경됩니다.
    이 기능이 필요하지 않은 경우 `-t ./ron` 또는 `-t $PWD/ron`을(를) 사용하세요.
    - 1.2: 디렉토리 대상이 아닌 경우
    예를 들어 `-t /tmp/`을(를) 호출하면 `test.toml` 파일은 `/tmp/`의 하위 디렉토리에만 저장할 수 있으며, `/tmp` 자체를 덮어쓸 수 없습니다.
    이 기능이 필요하지 않은 경우 `-t /tmp/xx.toml`과 같은 완전한(디렉토리가 아닌) 파일 경로를 사용하세요.
- 2. `--save`를 호출하지 않은 경우 지정된 파일이 자동으로 저장되지 않습니다.
- 3. `--save`를 호출한 경우, conv 하위 명령의 입력 및 출력은 동일한 파일이 될 수 없습니다.
- 4. 변환된 파일에서 주석은 보존되지 않습니다."""

save = "이 옵션을 호출하면 `--to`로 지정된 파일이 저장됩니다."
