auto-detection-failed = "Набудани формат ба таври худкор муайян карда нашуд.Лутфан дастӣ муайян кунед."
conv-error = "Хатои конверсия"
currently-supported = "Рӯйхати форматҳои форматро дар айни замон дастгирӣ мекунад:"
"invalid-json1.0" = "Файл формати \"Json 1.0\" нест"
not-support-deser-sexp = "** Ҳанӯз дастгирӣ намешавад **: Табдилдиҳӣ аз `lisp S-Mounce's 'ба' дигар форматҳо»"
unknown-fmt = "Файзи файли номаълум"
unsupported = "Табдили формати дастгирӣнашаванда"
