auto-detection-failed = "ਆਟੋਮੈਟਿਕਲੀ ਫਾਰਮੈਟ ਨੂੰ ਆਪਣੇ ਆਪ ਖੋਜਣ ਵਿੱਚ ਅਸਫਲ.ਕਿਰਪਾ ਕਰਕੇ ਹੱਥੀਂ ਨਿਰਧਾਰਤ ਕਰੋ."
conv-error = "ਤਬਦੀਲੀ ਦੀ ਗਲਤੀ"
currently-supported = "ਮੌਜੂਦਾ ਸਮੇਂ ਸਹਿਯੋਗੀ ਫਾਰਮੈਟ ਸੂਚੀ:"
dst = "ਟਿਕਾਣਾ ਫਾਈਲ ਮਾਰਗ"
"invalid-json1.0" = "ਫਾਈਲ ਇੱਕ ਵੈਧ `jonn 1.0 ਦਾ ਫਾਰਮੈਟ ਨਹੀਂ ਹੈ, `json5` ਦੇ ਪਾਰਸ ਕਰਨ ਦੀ ਕੋਸ਼ਿਸ਼ ਕਰ ਰਿਹਾ ਹੈ ..."
not-included = """
ਇਸ ਬਾਈਨਰੀ ** ਸ਼ਾਮਲ ਨਹੀਂ ਕਰਦਾ ** ਸੰਬੰਧਿਤ ਫਾਰਮੈਟ ਲਈ ਪਰਿਵਰਤਨ ਕਾਰਜਸ਼ੀਲਤਾ.
ਤੁਹਾਨੂੰ ਆਪਣੇ `ਕਾਰਗੋ.ਟੌਮਲ` ਅਤੇ ਮੁੜ ਕੰਪਾਇਲ ਵਿੱਚ ਸੰਬੰਧਿਤ ਵਿਸ਼ੇਸ਼ਤਾ ਨੂੰ ਸਮਰੱਥ ਕਰਨ ਦੀ ਜ਼ਰੂਰਤ ਹੈ.
ਜੇ ਇਸ ਸਾੱਫਟਵੇਅਰ ਵਿੱਚ ਅਨੁਸਾਰੀ ਕਾਰਜਸ਼ੀਲਤਾ ਸ਼ਾਮਲ ਨਹੀਂ ਹੈ, ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਮੁੱਦਾ ਪੇਸ਼ ਕਰੋ."""
not-support-deser-sexp = "** ਅਜੇ ਤੱਕ ਸਹਿਯੋਗੀ ਨਹੀਂ ਹੈ **: `ਲਿਸਪ ਐਸ-ਸਮੀਕਰਨ` ਤੋਂ` ਹੋਰ ਫਾਰਮੈਟਾਂ ਵਿੱਚ ਤਬਦੀਲ ਕਰਨਾ"
unknown-fmt = "ਅਣਜਾਣ ਫਾਇਲ ਫਾਰਮੈਟ"
unsupported = "ਅਸਮਰਥਿਤ ਫਾਰਮੈਟ ਪਰਿਵਰਤਨ"
