auto-detection-failed = "ફોર્મેટને આપમેળે શોધવામાં નિષ્ફળ.કૃપા કરીને મેન્યુઅલી સ્પષ્ટ કરો."
conv-error = "રૂપાંતર ભૂલ"
currently-supported = "હાલમાં સપોર્ટેડ ફોર્મેટ્સ સૂચિ:"
dst = "ગંતવ્ય ફાઇલ પાથ"
"invalid-json1.0" = "ફાઇલ માન્ય નથી `json 1.0` ફોર્મેટ, `json5` તરીકે વિશ્લેષણ કરવાનો પ્રયાસ કરી રહ્યો છે ..."
not-included = """
આ દ્વિસંગી ** સંબંધિત ફોર્મેટ માટે રૂપાંતર કાર્યક્ષમતા ** શામેલ નથી.
તમારે તમારા `કાર્ગો.ટ om મલ અને ફરીથી કમ્પાઇલમાં સંબંધિત સુવિધાને સક્ષમ કરવાની જરૂર છે.
જો આ સ software ફ્ટવેરને અનુરૂપ વિધેય શામેલ નથી, તો કૃપા કરીને કોઈ મુદ્દો સબમિટ કરો."""
not-saved = "નીચેની સામગ્રી સાચવવામાં આવશે નહીં કારણ કે `--save` કહેવામાં આવતું ન હતું."
not-support-deser-sexp = "** હજી સુધી સપોર્ટેડ નથી **: `લિસ્પ એસ-એક્સપ્રેસન` થી` અન્ય બંધારણોમાં રૂપાંતરિત કરવું"
unknown-fmt = "અજ્ unknown ાત ફાઇલ ફોર્મેટ"
unsupported = "અસમર્થિત ફોર્મેટ રૂપાંતર"
