auto-detection-failed = "ລົ້ມເຫລວໃນການກວດພົບຮູບແບບໂດຍອັດຕະໂນມັດ.ກະລຸນາລະບຸດ້ວຍຕົນເອງ."
conv-error = "ຂໍ້ຜິດພາດໃນການແປງ"
currently-supported = "ປະຈຸບັນສະຫນັບສະຫນູນບັນຊີລາຍຊື່ຮູບແບບ:"
dst = "ເສັ້ນທາງໄຟລ໌ປາຍທາງ"
not-included = """
Binary ນີ້ ** ບໍ່ລວມເອົາ ** ການເຮັດວຽກຂອງການປ່ຽນໃຈເຫລື້ອມໃສສໍາລັບຮູບແບບທີ່ກ່ຽວຂ້ອງ.
ທ່ານຈໍາເປັນຕ້ອງເປີດໃຊ້ຄຸນສົມບັດທີ່ກ່ຽວຂ້ອງໃນ `Cargo.Toml` ແລະ recompile.
ຖ້າຊອບແວນີ້ບໍ່ໄດ້ລວມເອົາການເຮັດວຽກທີ່ສອດຄ້ອງກັນ, ກະລຸນາສົ່ງບັນຫາ."""
not-support-deser-sexp = "** ບໍ່ໄດ້ຮັບການສະຫນັບສະຫນູນເທື່ອ"
unknown-fmt = "ຮູບແບບເອກະສານທີ່ບໍ່ຮູ້ຈັກ"
unsupported = "ການແປງຮູບແບບທີ່ບໍ່ໄດ້ຮັບການສະຫນັບສະຫນູນ"
