auto-detection-failed = "Форматыг автоматаар илрүүлж чадсангүй.Гараар тодорхойлно уу."
conv-error = "Хөрвүүлэх алдаа"
currently-supported = "Одоогийн байдлаар дэмжигдсэн форматын жагсаалт:"
dst = "Зорилтот файлын зам"
not-included = """
Энэ хоёртын ** нь холбогдох форматын хувьд хувиргах функцийг агуулаагүй байна.
Та `ачааны` ачааны.toml` ба Recompile-д холбогдох функцийг идэвхжүүлэх хэрэгтэй.
Хэрэв энэ програм нь холбогдох функцийг оруулаагүй бол асуудлыг илгээнэ үү."""
not-support-deser-sexp = "** дэмжигдээгүй байгаа хараахан дэмжигдээгүй байна **: `LISP S илэрхийлэх 'нь` Бусад Formats` руу хөрвүүлэх"
unknown-fmt = "File File Forment"
unsupported = "Дэмжигдээгүй форматыг хөрвүүлэх"
