auto-detection-failed = "स्वरूप स्वयंचलितपणे शोधण्यात अयशस्वी.कृपया व्यक्तिचलितपणे निर्दिष्ट करा."
conv-error = "रूपांतरण त्रुटी"
currently-supported = "सध्या समर्थित स्वरूपांची यादी:"
dst = "गंतव्य फाइल पथ"
"invalid-json1.0" = "फाईल वैध नाही `json 1.0` स्वरूप, `json5` म्हणून विश्लेषित करण्याचा प्रयत्न करीत आहे ..."
not-included = """
या बायनरी ** मध्ये संबंधित स्वरूपासाठी ** रूपांतरण कार्यक्षमता समाविष्ट नाही.
आपल्याला आपल्या `Caggo.toml` आणि recompile मधील संबंधित वैशिष्ट्य सक्षम करण्याची आवश्यकता आहे.
या सॉफ्टवेअरमध्ये संबंधित कार्यक्षमता समाविष्ट नसल्यास, कृपया एक समस्या सबमिट करा."""
not-support-deser-sexp = "** अद्याप समर्थित नाही **: `लिस्प एस-एक्सप्रेशन` पासून `इतर स्वरूपात रूपांतरित करणे"
unknown-fmt = "अज्ञात फाइल स्वरूप"
unsupported = "असमर्थित स्वरूप रूपांतरण"
