auto-detection-failed = "ଫର୍ମାଟ୍ ଚିହ୍ନଟ କରିବାରେ ବିଫଳ ହେଲା |ଦୟାକରି ହସ୍ତକୃତ ଭାବରେ ନିର୍ଦ୍ଦିଷ୍ଟ କରନ୍ତୁ |"
conv-error = "ରୂପାନ୍ତର ତ୍ରୁଟି |"
currently-supported = "ସମ୍ପ୍ରଦାୟ ଫର୍ମାଟ୍ ତାଲିକା:"
dst = "ଗନ୍ତବ୍ୟସ୍ଥଳ ଫାଇଲ୍ ପଥ |"
"invalid-json1.0" = "ଫାଇଲଟି ଏକ ବ valid ଧ `json 1.0` ଫର୍ମାଟ୍ ନୁହେଁ, `JSON5` ଭାବରେ ବିଶ୍ଳେଷଣ କରିବାକୁ ଚେଷ୍ଟା କରୁଛି ..."
not-included = """
ଏହି ବାଇନାରୀ ** ଅନ୍ତର୍ଭୂକ୍ତ କରେ ନାହିଁ ** ପ୍ରଯୁଜ୍ୟ ଫର୍ମାଟ୍ ପାଇଁ ରୂପାନ୍ତର କାର୍ଯ୍ୟକାରିତା |
ତୁମର `କାର୍ଗୋ.ଟୋମୋଲରେ ସମ୍ପୃକ୍ତ ବ feature ଶିଷ୍ଟ୍ୟ ସକ୍ଷମ କରିବାକୁ ପଡିବ ଏବଂ ପୁନ ompmpililed |
ଯଦି ଏହି ସଫ୍ଟୱେର ନିର୍ଦ୍ଦିଷ୍ଟ କାର୍ଯ୍ୟକାରିତା ଅନ୍ତର୍ଭୂକ୍ତ କରେ ନାହିଁ, ଦୟାକରି ଏକ ସମସ୍ୟା ଦାଖଲ କରନ୍ତୁ |"""
unknown-fmt = "ଅଜ୍ଞାତ ଫାଇଲ୍ ଫର୍ମାଟ୍ |"
unsupported = "ଅସମର୍ଥିତ ଫର୍ମାଟ୍ ରୂପାନ୍ତର |"
