auto-detection-failed = "ไม่สามารถตรวจจับรูปแบบได้โดยอัตโนมัติโปรดระบุด้วยตนเอง"
conv-error = "ข้อผิดพลาดการแปลง"
currently-supported = "รายการรูปแบบที่รองรับในปัจจุบัน:"
dst = "เส้นทางไฟล์ปลายทาง"
"invalid-json1.0" = "ไฟล์ไม่ได้เป็นรูปแบบ `JSON 1.0` ที่ถูกต้องพยายามแยกวิเคราะห์เป็น `json5` ..."
not-included = """
ไบนารี ** นี้ไม่รวม ** ฟังก์ชั่นการแปลงสำหรับรูปแบบที่เกี่ยวข้อง
คุณต้องเปิดใช้งานคุณสมบัติที่เกี่ยวข้องใน `Cargo.toml` และ repompile
หากซอฟต์แวร์นี้ไม่รวมฟังก์ชั่นที่เกี่ยวข้องโปรดส่งปัญหา"""
not-saved = "เนื้อหาต่อไปนี้ ** จะไม่ถูกบันทึกไว้เพราะ `--save` ไม่ถูกเรียก"
not-support-deser-sexp = "** ยังไม่รองรับ **: การแปลงจาก `Lisp S-Expression` เป็น` รูปแบบอื่น ๆ '"
unknown-fmt = "รูปแบบไฟล์ที่ไม่รู้จัก"
unsupported = "การแปลงรูปแบบที่ไม่ได้รับการสนับสนุน"
