auto-detection-failed = "Не вдалося автоматично виявити формат.Будь ласка, вкажіть вручну."
conv-error = "Помилка перетворення"
currently-supported = "Список форматів, що підтримуються в даний час:"
dst = "шлях призначення"
"invalid-json1.0" = "Файл не є дійсним форматом json 1.0`, намагаючись розібратися як `json5` ..."
not-included = """
Цей двійковий ** не включає ** функціональність перетворення для відповідного формату.
Вам потрібно ввімкнути відповідну функцію у вашому `Cargo.toml` та перекомпілювати.
Якщо це програмне забезпечення не включає відповідну функціональність, надішліть проблему."""
not-saved = "Наступний вміст ** не буде збережено, оскільки `--save` не викликали."
not-support-deser-sexp = "4"
unknown-fmt = "Невідомий формат файлу"
unsupported = "Небудова перетворення формату"
