auto-detection-failed = "په اوتومات ډول یې ب format ه کشف کول ونشول.مهرباني وکړئ په لاسي ډول مشخص کړئ."
conv-error = "د بدلولو تېروتنه"
currently-supported = "اوس مهال د بیمې ملاتړ شوي فارمیټونو لیست:"
dst = "منزل دوتنې لار"
"invalid-json1.0" = "فایل د اعتبار وړ `JSon 1.0` ب format ه نه ده، هڅه کوي د `json5```````` ... ..."
not-included = """
دا بائنری ** د اړونده ب format ې لپاره د تبادلې فعالیت کې شامل ندي ** د تبادلې فعالیت.
تاسو اړتیا لرئ په خپل `کارګو ایوټول او بیا تنظیمولو کې اړونده ب feature ه وړ کړئ.
که چیرې دا سافټویر ورته فعالیت نه وي، مهرباني وکړئ یوه مسله وسپارئ."""
not-support-deser-sexp = "Whoc نه دی ملاتړ **: د `لیپس ایس ایس ایس ای څرګندول 'او نور بمونه"
unknown-fmt = "نامعلومه دوتنه"
unsupported = "د ناملاتړی نښه"
