auto-detection-failed = "បានបរាជ័យក្នុងការរកឃើញទ្រង់ទ្រាយដោយស្វ័យប្រវត្តិ។សូមបញ្ជាក់ដោយដៃ។"
conv-error = "ការបំលែងកំហុសកំហុស"
currently-supported = "បញ្ជីទ្រង់ទ្រាយដែលបានគាំទ្របច្ចុប្បន្ន:"
dst = "ផ្លូវឯកសារទិសដៅ"

not-support-deser-sexp = "មិនត្រូវបានគាំទ្រនៅឡើយទេប៉ុន្តែ **: ការបំលែងពី `lisp s-callment` ទំរង់ផ្សេងទៀត"
unknown-fmt = "មិនស្គាល់ទ្រង់ទ្រាយឯកសារ"
unsupported = "ការបំលែងទ្រង់ទ្រាយដែលមិនបានគាំទ្រ"
