auto-detection-failed = "ვერ მოხერხდა ფორმატის ავტომატურად გამოვლენა.გთხოვთ მიუთითოთ ხელით."
conv-error = "კონვერტაციის შეცდომა"
currently-supported = "ამჟამად მხარდაჭერილი ფორმატების სია:"
dst = "დანიშნულების ფაილის გზა"
not-included = """
ეს ორობითი ** არ შეიცავს ** კონვერტაციის ფუნქციონირებას შესაბამისი ფორმატისთვის.
თქვენ უნდა ჩართოთ შესაბამისი ფუნქცია თქვენს `Cargo.toml` და ანაზღაურება.
თუ ეს პროგრამა არ შეიცავს შესაბამის ფუნქციონირებას, გთხოვთ, წარუდგინოთ საკითხი."""
not-saved = "შემდეგი შინაარსი ** არ შეინახება, რადგან `--save` არ დაურეკეს."
unknown-fmt = "უცნობი ფაილის ფორმატი"
unsupported = "დაუსაბუთებელი ფორმატის კონვერტაცია"
