auto-detection-failed = "Није успело аутоматски открити формат.Молимо наведите ручно."
conv-error = "Грешка у конверзији"
currently-supported = "Тренутно подржана листа формата:"
dst = "Стаза одредишта одредишта"
"invalid-json1.0" = "Датотека није валидна формата `Јсон 1.0`, покушавајући да анализира као` ЈСОН5` ..."
not-included = """
Овај бинарни ** не укључује ** функционалност конверзије за одговарајући формат.
Морате да омогућите релевантну карактеристику у вашем `Царго.Томл` и поновној композицији.
Ако овај софтвер не укључује одговарајућу функционалност, молимо да поднесете проблем."""
not-saved = "Следећи садржај ** неће ** бити сачуван јер `--save` није звао."
not-support-deser-sexp = "** Још није подржана **: Претварање из `ЛИСП С-експресије` у` остале формате`"
unknown-fmt = "Непознати формат датотеке"
unsupported = "Неподржани формат формат"
