auto-detection-failed = "ניט אַנדערש צו דעטאַילס די פֿאָרמאַט.ביטע ספּעציפיצירן מאַניואַלי."
conv-error = "קאַנווערזשאַן טעות"
currently-supported = "דערווייַל געשטיצט פֿאָרמאַטירונגען רשימה:"
dst = "דעסטיניישאַן טעקע דרך"
"invalid-json1.0" = "דער טעקע איז נישט אַ גילטיק `json 1.0` פֿאָרמאַט, טריינג צו פּאַרס ווי `json5` ..."
not-support-deser-sexp = "** ניט געשטיצט נאָך **: קאַנווערטינג פון `ליספּ ס-אויסדרוק` צו` אנדערע פאָרמאַץ`"
unknown-fmt = "אומבאַקאַנט טעקע פֿאָרמאַט"
unsupported = "ניט-סופּפּאָרטעד פֿאָרמאַט קאַנווערזשאַן"
