auto-detection-failed = "فشل الكشف التلقائي عن التنسيق. يرجى تحديده يدويًا."
conv-error = "خطأ في التحويل"
currently-supported = "قائمة التنسيقات المدعومة حاليًّا:"
dst = "مسار ملف الوجهة"
"invalid-json1.0" = "الملف ليس بتنسيق `json 1.0` صالح ، جاري محاولة التحويل إلى `json5` ..."
not-included = """
لا يتضمن هذا البرنامج الثنائي **عملية التحويل** للتنسيق ذي الصلة.
يجب تمكين الميزة المناسبة في ملف `Cargo.toml` الخاص بك وإعادة الترجمة.
إذا لم يتضمن هذا البرنامج الثنائي الوظائف المناسبة، يرجى إرسال طلب في القائمة."""
not-saved = "لن يتم حفظ المحتوى التالي **لأن `--save` لم يتم استدعاؤه**."
not-support-deser-sexp = "**غير مدعوم حاليًا**: التحويل من تنسيق `Lisp S-Expression` إلى `تنسيقات أخرى`"
unknown-fmt = "تنسيق الملف غير معروف"
unsupported = "تحويل التنسيق غير المدعوم"
