auto-detection-failed = "स्वचालित रूपमा ढाँचा पत्ता लगाउन असफल भयो।कृपया मैन्युअल्ली निर्दिष्ट गर्नुहोस्।"
conv-error = "रूपान्तरण त्रुटि"
currently-supported = "हाल प्रशस्त फोरट्स सूची प्रदान गर्दछ:"
dst = "गन्तव्य फाइल पथ"
"invalid-json1.0" = "फाईल मान्य `jon 1.0` ormant jstee,` JNON5`` को रूपमा पार्स गर्न कोशिस गर्दै छैन,"
not-included = """
यो बाइनरी ** ** सान्दर्भिक ढाँचाको लागि रूपान्तरण कार्यक्षमता समावेश गर्दैन।
तपाइँ तपाइँको `Change.tomll` र replatile मा सान्दर्भिक सुविधा सक्षम गर्न आवश्यक छ।
यदि यो सफ्टवेयरले सम्बन्धित कार्यक्षमता समावेश गर्दैन भने कृपया एक मुद्दा बुझाउनुहोस्।"""
not-support-deser-sexp = "** / * समर्थित छैन **: `लिट्स एस-अभिव्यक्तिबाट रूपान्तरण गर्दै - अन्य ढाँचाहरू"
unknown-fmt = "अज्ञात फाइल ढाँचा"
unsupported = "असमर्थित ढाँचा रूपान्तरण"
